name: Flutter

on:
  push:
    branches: [ "mistress" ]
  pull_request:
    branches: [ "mistress" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.14.0

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze --no-congratulate --no-preamble --no-pub

      - name: Run tests
        run: flutter test --coverage --no-pub --file-reporter json:tests.json

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Convert test results to JUnit format
        run: |
          dart pub global activate junitreport
          dart pub global run junitreport:tojunit --input tests.json --output junit.xml

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
